part of '../product_studio_controller.dart';

extension ProductStudioControllerUpdate on ProductStudioController {
  void updateField({
    String? title, String? arabicTitle, String? sku, String? barcode, List<String>? multiBarcodes,
    String? category, String? subcategory,
    String? brand, String? subBrand, String? manufacturer,
    String? status, String? productLifecycleStatus, String? visibility,
    String? countryOfOrigin, String? manufacturerPartNumber, String? vendorSku, String? internalBarcode,
    DateTime? launchDate, DateTime? discontinueDate,
    String? marketingTitle, String? shortDescription, String? description, String? metaDescription,
    String? urlSlug, String? tags, List<String>? searchKeywords, String? promotionalBadges,
    String? primaryImageUrl, List<String>? galleryUrls, bool? featuredProduct, String? targetAudience,
    String? seoTitle, String? sectorId, String? departmentId, String? subDepartmentId,
    String? productType, String? segment,
    bool? appVisibility, bool? b2bVisibility,
    double? costPrice, double? sellingPrice, double? mrp, double? wholesalePrice,
    double? onlinePrice, double? memberLoyaltyPrice, double? loyaltyPointsMultiplier,
    String? discountType, double? discountValue, double? maxDiscountPct,
    bool? autoComputeLandedCost, bool? isLiveMarketPrice, DateTime? priceEffectiveFrom,
    String? currency, double? targetMarginPct, double? targetMarkupPct, double? branchSellingPrice,
    bool? trackInventory, bool? allowNegativeStock, double? openingStock,
    int? minStock, int? safetyStock,
    int? maxStock, double? reorderLevel, String? warehouseLocation, String? stockUnit,
    String? salesUnit, String? purchaseUnit, double? conversionFactor,
    double? grossWeight, double? netWeight, double? tareWeight, String? unitDimensions,
    String? packageType, int? unitsPerPackage, double? packageQuantity,
    double? packagingDeposit, double? packagingCost, double? containerDepositFee,
    String? storageClass, String? storageCondition, String? floorZone,
    bool? coldStorageIndicator, bool? coldChainRequired, String? logisticsSlab,
    String? volumetricWeight, String? countryRestrictions, String? valuationMethod,
    int? leadTimeBuffer, bool? autoReplenish, int? innerPackQuantity,
    String? taxStatus, String? taxCategory, double? taxRate, String? taxJurisdiction,
    String? taxCode, String? gstTaxMode, String? taxTreatment, String? vatCategory,
    String? selectiveExciseTax, String? zatcaCode, String? sacCode, String? hsnCode,
    String? taxExemptionNo, String? importDutyClass,
    String? supplier, String? secondarySupplier, String? supplierProductCode,
    String? supplierProductName, double? supplierPurchaseCost, int? supplierMOQ,
    int? supplierLeadTime, String? supplierPaymentTerms, String? supplierContact,
    String? supplierNotes, String? primarySupplierId, String? supplierSku,
    double? vendorContractCost, double? supplierMoq,
    String? pluCode, String? unit, String? posShortThermalName, String? posReceiptName,
    bool? isQuickPOSSale, bool? posHotkeyEnabled, bool? posAgeGate,
    String? posManualDiscount, String? posPriceOverride, String? eslId,
    String? rfidTagId, String? aisleLocation, String? planogramId,
    int? minDisplayQty, int? maxDisplayQty, bool? isEasTagRequired, bool? mandatorySerialScan,
    String? planogramAisle, String? planogramBay, String? planogramRack, String? planogramShelf,
    String? planogramBin, String? planogramEndcap, bool? cashierOverride, double? maxCashierDisc,
    bool? priceFloorLock, double? promotionalPrice,
    bool? batchExpiryMandatory, bool? breakBulkAllowed, bool? caseSerialTracking,
    bool? mtcRequired, bool? bulkNarcoticLogging, bool? coldChainLogger,
    bool? enableBatchTracking, bool? enableExpiryTracking,
    int? expiryWarningThreshold, int? expiryAlertThreshold,
    int? freshnessDuration, String? freshnessUnit,
    int? unitsPerStrip, bool? allowLooseBilling,
    bool? capWeighed, bool? capPluCode, bool? capBulk, bool? capRepack,
    bool? capTare, bool? capCatchWeight, bool? capVariant, bool? capDeposit,
    bool? capColdChain, bool? capAgeRestriction,
    String? scaleMode, String? pluType, String? bulkSourceProduct,
    double? availableBulkQuantity, String? repackSourceProduct,
    double? repackConversionRatio, double? minWeight, double? maxWeight,
    String? tareMode, int? minAge,
    String? legalReference, String? depositType, double? depositAmount,
    String? variantGroup, String? variantType,
    String? periodAfterOpening, bool? isRecalledBatch,
    String? inspectionId, String? rfidId, String? productRelationship,
    String? warrantyInfo, bool? warrantyAvailable, int? warrantyDuration,
    String? warrantyUnit, String? warrantyContract, String? fragranceFamily,
    String? concentration, String? scentNotes, String? perfumeHouse,
    String? topNotes, String? middleNotes, String? baseNotes, String? ingredients,
    String? usageInfo, int? productionLeadTime, String? brandRange,
    String? skinType, String? hairType, String? volume, bool? sparePartsBreakdown,
    double? abv, bool? ageGate, double? baleWeight, double? rollLength,
    bool? isCatchWeight, int? scaleWeightPrecision, double? variableWeightTolerance,
    double? tareWeightDeduction, String? unitPriceComparisonBase,
    bool? isCrossDockingAllowed, bool? isVmiEnabled, bool? inHouseRepack,
    String? nicotineContent, bool? passportVerificationRequired,
    bool? flightNumberRequired, double? multiBuyBundlePrice, int? multiBuyQtyTrigger,
    int? multiBuyMaxQtyPerBill, double? compensationCess, double? minOrderValue,
    String? temperatureProfile, String? cosmeticGrade, String? batteryHealth,
    String? sellerWarranty, String? replacedParts, double? peakOutput,
    String? solarChargeController, String? nightVision, String? focalLength,
    bool? inverterTechnology, bool? dishwasherSafe, bool? originalBoxIncluded,
    bool? pureSineWave, bool? obstacleAvoidance, bool? nightVisionEnabled,
    bool? seasonalProduct, bool? isFoldable,
    bool? isMotorized, bool? isRentalAvailable, bool? fastMovingFlag,
    String? takeoffWeight, String? flightTime, String? transmissionRange,
    String? batteryChemistry, String? template, int? ageRestriction,
    BusinessScale? businessScale, dynamic itemType, String? businessType,
    String? businessCategory, String? stallAssignment, double? managementRoyaltyPct,
    String? foodCategory, String? ingredientsSummary, List<String>? dietaryBadges,
    List<String>? cupSizes, List<String>? fruitBases, List<ComboItem>? comboItems,
    bool? allowRoomFolio, double? roomDeliveryCharge, double? takeawaySurcharge,
    bool? variableWeightPLU, List<String>? channelEligibility, String? division,
    bool? privateLabel, String? posHotkeyColor, String? cancellationPolicy,
    String? repairCustomerImei, String? repairComplaintLog,
    String? hotelDepartment, String? juiceCategory, String? cafeCategory, String? bakeryType,
    String? digitalMenuDescription, String? preparationSlaWindow, String? fineDiningCourse,
    String? winePairing, String? kdsCategory, String? kotStation, String? foodClass,
    String? spiceLevel, List<String>? allergens, double? calories, int? prepTime,
    int? courseFireDelay, String? recipeVersion, String? recipePrepNotes,
    double? nutritionalProtein, double? nutritionalCarbs, double? nutritionalTransFats,
    String? nutritionalBreakdown, double? dineInPrice, double? takeawayPrice,
    double? aggregatorPrice, double? packagingSurcharge, double? roomServiceMarkupPct,
    double? paxPrice, double? targetFoodCostPct, bool? isExpressPrep,
    bool? customMessageAllowed, bool? extraShotAllowed, bool? isRoomServiceAvailable,
    String? swiggySku, String? zomatoSku, String? uberEatsSku, String? talabatSku,
    String? flavorProfile, List<String>? sugarLevels, List<String>? milkOptions,
    String? portionSize, bool? isCombo, String? virtualBrand, bool? readyToEatItem,
    String? cuisineType, DateTime? bakeTimestamp, double? serviceChargePct,
    String? apparelCategory, String? styleCategory, String? season, String? material,
    String? fabricComposition, String? patternDesign, String? fitType,
    String? sleeveNeckType, String? careGuide, String? artisanLabel, String? collectionEdition,
    String? soleMaterial, String? closureType, String? widthFit, String? sizeStandard,
    String? gender, String? targetAgeGroup, bool? exclusiveSinglePiece, bool? madeToOrder,
    String? measurementBust, String? measurementWaist, String? measurementHip,
    String? measurementFullLength, String? measurementProfile, String? colorFinish,
    String? shade, String? shadeHexColor,
    String? therapeuticCategory, String? indicationCategory, String? drugSchedule,
    String? genericSalt, String? dosageForm, String? prescriptionClass, bool? isNarcotic,
    String? healthLicense, List<String>? assignedDoctors, String? dentalQuadrant,
    bool? consentRequired, String? specimenType, String? fastingRequirement,
    int? tat, String? labRouting, String? referenceRange, String? deviceTrackingType,
    int? calibrationFrequency, bool? biomedicalTraining, String? hazardousGrade,
    String? modelNumber, String? partNumber, String? oemNumber, String? serialNumber,
    String? imei, String? compatibility, String? ramSize, String? internalStorage,
    String? chipset, String? screenSize, String? batteryCapacity, String? connectivity,
    String? simSlots, String? processor, String? ramGeneration, String? dedicatedGpu,
    String? osVersion, String? audioType, String? driverSize, String? bluetoothVersion,
    String? batteryLife, String? panelTechnology, String? resolution,
    String? refreshRate, String? smartTvOs, String? hdrFormat, String? hdmiPorts,
    String? energyRating, String? refrigerantType, double? annualEnergyConsumption,
    String? motorWattage, String? jarCapacity, String? speedControls,
    String? heatingElements, String? gamingPlatform, String? gamingEdition,
    int? controllerCount, String? includedGames, String? sensorType,
    String? megapixels, String? lensMount, String? maxVideoResolution,
    String? isoRange, String? imageStabilization, String? shutterRating,
    bool? fastChargingSupported, bool? ancSupported,
    String? metalType, String? purity, String? stoneType, double? weight, double? stoneWeight,
    String? jewelrySize, int? gemstoneCount, String? makingChargeMode,
    double? makingChargeRate, double? wastagePct, String? liveRateLink,
    List<String>? safetyCertifications, String? containerType, String? cakeSize,
    String? cakeShape, String? cakeFilling, String? cakeFrosting,
    String? coffeeServingTemp, String? barPourMetric, String? mealPlanInclusions,
    String? eventType, String? setupInclusions, String? selfMedicationWarning,
    String? controlledRegisterId, String? masterMoleculeCode, String? genericAlternative,
    String? homeopathyLatinName, String? homeopathyPotencyScale, String? homeopathyDilution,
    String? homeopathyMotherTincture, String? biocompatibilityGrade,
    String? weightCapacity, String? rentalPeriod, String? reagentType,
    String? reagentSensitivity, String? curingTime, String? settingExpansion,
    String? targetSpecies, String? animalWeightRange, String? meatWithdrawalPeriod,
    String? milkWithdrawalPeriod, String? activeNutrient, double? minStorageTemp,
    double? maxStorageTemp, double? maxRoomTempExposure, double? nutrientPercentage,
    bool? substitutionAllowed, DateTime? contractPricingEffectiveFrom,
    DateTime? contractPricingEffectiveTo, DateTime? scheduledTrialDate,
    DateTime? promisedDeliveryDate,
    String? masterTradeSku, String? primaryTradeUnit, String? tradeCreditTerms,
    String? temperatureStorage, String? prePackRatio, String? shrinkageGrade,
    String? materialGrade, String? freightClass, String? industrialUom,
    String? incoterms, String? freightSurcharge, String? gaugeThickness,
    String? rmaPolicy, String? tierUomMapping, String? returnPolicy,
    String? customsPortOfEntry, String? ssccBarcode, String? masterOuterBarcode,
    double? masterCaseRatio, int? caseMultiplier, int? palletStacking,
    String? organicCertification, String? organicCertNo, bool? organicCertified,
    String? farmTraceabilityId, DateTime? harvestDate,
    String? serviceCategory, String? serviceDeliveryMode, int? serviceDuration,
    String? serviceDurationUnit, String? billingModel, int? bufferTime,
    String? therapistRoom, double? staffCommissionRate, String? pricingMetric,
    List<String>? careTreatments, List<String>? allocatedStaff, double? diagnosisCharge,
    String? serviceWarranty, String? slaPriority, String? consultationFormat,
    String? meetingPlatform, String? batchTiming, bool? courseMaterialProvided,
    int? batchSeatCapacity, String? membershipFrequency, String? trainerInclusion,
    List<String>? accessPrivileges, double? admissionFee, String? pausePolicy,
    String? resourceAssignment, int? advanceBookingHours, double? advanceDepositPct,
    double? buyerCreditLimit, String? assignedSalesRepresentative,
    String? territoryAllocation, bool? isAppointmentRequired,
    String? opticalProductType, String? lensIndex, List<String>? lensCoating,
    String? frameParameters, String? optometrySph, String? optometryCyl,
    String? optometryAxis, String? optometryBaseCurve, String? optometryDiameter,
    String? optometryMoistureContent, String? optometryReplacementSchedule,
    String? udiCode, String? implantType, String? classicalReference,
    String? vehicleMake, String? vehicleModel, String? operatingVoltage,
    String? mountingType, String? packageForm, int? pinCount,
    String? networkingDeviceType, String? portConfig, String? wirelessBandwidth,
    String? iotProtocol, String? weatherproofRating, bool? poeSupported,
    bool? rackMountable,
    String? dataLoggerSerialId, DateTime? sterilizationExpiry,
    // Healthcare / pharma dosage descriptors.
    String? potency, int? stripsPerBox, String? formulationType,
    String? adjuvantVehicle, String? servingSize, String? serviceProcedureType,
    String? drugLicenseWholesale,
    // Classification & regulatory identity.
    String? productClassification, String? complianceId, String? brandType,
    String? barcodeType, String? subDepartment, String? hallmarkCert,
    DateTime? manufacturingDate,
    // F&B specific descriptors.
    String? bakeryShelfLife, String? barLiquorClass, int? minPax,
    // Product relationship graph.
    String? parentSku,
  }) {
    final p = _product;
    _updateCoreFields(p, title: title, arabicTitle: arabicTitle, sku: sku, barcode: barcode, multiBarcodes: multiBarcodes, category: category, subcategory: subcategory, brand: brand, subBrand: subBrand, manufacturer: manufacturer, status: status, productLifecycleStatus: productLifecycleStatus, visibility: visibility, countryOfOrigin: countryOfOrigin, manufacturerPartNumber: manufacturerPartNumber, vendorSku: vendorSku, internalBarcode: internalBarcode, launchDate: launchDate, discontinueDate: discontinueDate, marketingTitle: marketingTitle, shortDescription: shortDescription, description: description, metaDescription: metaDescription, urlSlug: urlSlug, tags: tags, searchKeywords: searchKeywords, promotionalBadges: promotionalBadges, primaryImageUrl: primaryImageUrl, galleryUrls: galleryUrls, featuredProduct: featuredProduct, targetAudience: targetAudience, seoTitle: seoTitle, sectorId: sectorId, departmentId: departmentId, subDepartmentId: subDepartmentId, productType: productType, segment: segment, appVisibility: appVisibility, b2bVisibility: b2bVisibility);
    _updateEnterpriseFields(p, costPrice: costPrice, sellingPrice: sellingPrice, mrp: mrp, wholesalePrice: wholesalePrice, onlinePrice: onlinePrice, memberLoyaltyPrice: memberLoyaltyPrice, loyaltyPointsMultiplier: loyaltyPointsMultiplier, discountType: discountType, discountValue: discountValue, maxDiscountPct: maxDiscountPct, autoComputeLandedCost: autoComputeLandedCost, isLiveMarketPrice: isLiveMarketPrice, priceEffectiveFrom: priceEffectiveFrom, currency: currency, targetMarginPct: targetMarginPct, targetMarkupPct: targetMarkupPct, branchSellingPrice: branchSellingPrice, trackInventory: trackInventory, allowNegativeStock: allowNegativeStock, openingStock: openingStock, minStock: minStock, safetyStock: safetyStock, maxStock: maxStock, reorderLevel: reorderLevel, warehouseLocation: warehouseLocation, stockUnit: stockUnit, salesUnit: salesUnit, purchaseUnit: purchaseUnit, conversionFactor: conversionFactor, grossWeight: grossWeight, netWeight: netWeight, tareWeight: tareWeight, unitDimensions: unitDimensions, packageType: packageType, unitsPerPackage: unitsPerPackage, packageQuantity: packageQuantity, packagingDeposit: packagingDeposit, packagingCost: packagingCost, containerDepositFee: containerDepositFee, storageClass: storageClass, storageCondition: storageCondition, floorZone: floorZone, coldStorageIndicator: coldStorageIndicator, coldChainRequired: coldChainRequired, logisticsSlab: logisticsSlab, volumetricWeight: volumetricWeight, countryRestrictions: countryRestrictions, valuationMethod: valuationMethod, leadTimeBuffer: leadTimeBuffer, autoReplenish: autoReplenish, innerPackQuantity: innerPackQuantity, taxStatus: taxStatus, taxCategory: taxCategory, taxRate: taxRate, taxJurisdiction: taxJurisdiction, taxCode: taxCode, gstTaxMode: gstTaxMode, taxTreatment: taxTreatment, vatCategory: vatCategory, selectiveExciseTax: selectiveExciseTax, zatcaCode: zatcaCode, sacCode: sacCode, hsnCode: hsnCode, taxExemptionNo: taxExemptionNo, importDutyClass: importDutyClass, supplier: supplier, secondarySupplier: secondarySupplier, supplierProductCode: supplierProductCode, supplierProductName: supplierProductName, supplierPurchaseCost: supplierPurchaseCost, supplierMOQ: supplierMOQ, supplierLeadTime: supplierLeadTime, supplierPaymentTerms: supplierPaymentTerms, supplierContact: supplierContact, supplierNotes: supplierNotes, primarySupplierId: primarySupplierId, supplierSku: supplierSku, vendorContractCost: vendorContractCost, supplierMoq: supplierMoq, pluCode: pluCode, unit: unit, posShortThermalName: posShortThermalName, posReceiptName: posReceiptName, isQuickPOSSale: isQuickPOSSale, posHotkeyEnabled: posHotkeyEnabled, posAgeGate: posAgeGate, posManualDiscount: posManualDiscount, posPriceOverride: posPriceOverride, eslId: eslId, rfidTagId: rfidTagId, aisleLocation: aisleLocation, planogramId: planogramId, minDisplayQty: minDisplayQty, maxDisplayQty: maxDisplayQty, isEasTagRequired: isEasTagRequired, mandatorySerialScan: mandatorySerialScan, planogramAisle: planogramAisle, planogramBay: planogramBay, planogramRack: planogramRack, planogramShelf: planogramShelf, planogramBin: planogramBin, planogramEndcap: planogramEndcap, cashierOverride: cashierOverride, maxCashierDisc: maxCashierDisc, priceFloorLock: priceFloorLock, promotionalPrice: promotionalPrice);
    _updateIndustryFields(p, hotelDepartment: hotelDepartment, juiceCategory: juiceCategory, cafeCategory: cafeCategory, bakeryType: bakeryType, digitalMenuDescription: digitalMenuDescription, preparationSlaWindow: preparationSlaWindow, fineDiningCourse: fineDiningCourse, winePairing: winePairing, kdsCategory: kdsCategory, kotStation: kotStation, foodClass: foodClass, spiceLevel: spiceLevel, allergens: allergens, calories: calories, prepTime: prepTime, courseFireDelay: courseFireDelay, recipeVersion: recipeVersion, recipePrepNotes: recipePrepNotes, nutritionalProtein: nutritionalProtein, nutritionalCarbs: nutritionalCarbs, nutritionalTransFats: nutritionalTransFats, nutritionalBreakdown: nutritionalBreakdown, dineInPrice: dineInPrice, takeawayPrice: takeawayPrice, aggregatorPrice: aggregatorPrice, packagingSurcharge: packagingSurcharge, roomServiceMarkupPct: roomServiceMarkupPct, paxPrice: paxPrice, targetFoodCostPct: targetFoodCostPct, isExpressPrep: isExpressPrep, customMessageAllowed: customMessageAllowed, extraShotAllowed: extraShotAllowed, isRoomServiceAvailable: isRoomServiceAvailable, swiggySku: swiggySku, zomatoSku: zomatoSku, uberEatsSku: uberEatsSku, talabatSku: talabatSku, flavorProfile: flavorProfile, sugarLevels: sugarLevels, milkOptions: milkOptions, portionSize: portionSize, isCombo: isCombo, virtualBrand: virtualBrand, readyToEatItem: readyToEatItem, cuisineType: cuisineType, bakeTimestamp: bakeTimestamp, serviceChargePct: serviceChargePct, apparelCategory: apparelCategory, styleCategory: styleCategory, season: season, material: material, fabricComposition: fabricComposition, patternDesign: patternDesign, fitType: fitType, sleeveNeckType: sleeveNeckType, careGuide: careGuide, artisanLabel: artisanLabel, collectionEdition: collectionEdition, soleMaterial: soleMaterial, closureType: closureType, widthFit: widthFit, sizeStandard: sizeStandard, gender: gender, targetAgeGroup: targetAgeGroup, exclusiveSinglePiece: exclusiveSinglePiece, madeToOrder: madeToOrder, measurementBust: measurementBust, measurementWaist: measurementWaist, measurementHip: measurementHip, measurementFullLength: measurementFullLength, measurementProfile: measurementProfile, colorFinish: colorFinish, shade: shade, shadeHexColor: shadeHexColor, therapeuticCategory: therapeuticCategory, indicationCategory: indicationCategory, drugSchedule: drugSchedule, genericSalt: genericSalt, dosageForm: dosageForm, prescriptionClass: prescriptionClass, isNarcotic: isNarcotic, healthLicense: healthLicense, assignedDoctors: assignedDoctors, dentalQuadrant: dentalQuadrant, consentRequired: consentRequired, specimenType: specimenType, fastingRequirement: fastingRequirement, tat: tat, labRouting: labRouting, referenceRange: referenceRange, deviceTrackingType: deviceTrackingType, calibrationFrequency: calibrationFrequency, biomedicalTraining: biomedicalTraining, hazardousGrade: hazardousGrade, modelNumber: modelNumber, partNumber: partNumber, oemNumber: oemNumber, serialNumber: serialNumber, imei: imei, compatibility: compatibility, ramSize: ramSize, internalStorage: internalStorage, chipset: chipset, screenSize: screenSize, batteryCapacity: batteryCapacity, connectivity: connectivity, simSlots: simSlots, processor: processor, ramGeneration: ramGeneration, dedicatedGpu: dedicatedGpu, osVersion: osVersion, audioType: audioType, driverSize: driverSize, bluetoothVersion: bluetoothVersion, batteryLife: batteryLife, panelTechnology: panelTechnology, resolution: resolution, refreshRate: refreshRate, smartTvOs: smartTvOs, hdrFormat: hdrFormat, hdmiPorts: hdmiPorts, energyRating: energyRating, refrigerantType: refrigerantType, annualEnergyConsumption: annualEnergyConsumption, motorWattage: motorWattage, jarCapacity: jarCapacity, speedControls: speedControls, heatingElements: heatingElements, gamingPlatform: gamingPlatform, gamingEdition: gamingEdition, controllerCount: controllerCount, includedGames: includedGames, sensorType: sensorType, megapixels: megapixels, lensMount: lensMount, maxVideoResolution: maxVideoResolution, isoRange: isoRange, imageStabilization: imageStabilization, shutterRating: shutterRating, fastChargingSupported: fastChargingSupported, ancSupported: ancSupported, metalType: metalType, purity: purity, stoneType: stoneType, weight: weight, stoneWeight: stoneWeight, jewelrySize: jewelrySize, gemstoneCount: gemstoneCount, makingChargeMode: makingChargeMode, makingChargeRate: makingChargeRate, wastagePct: wastagePct, liveRateLink: liveRateLink, safetyCertifications: safetyCertifications, containerType: containerType, cakeSize: cakeSize, cakeShape: cakeShape, cakeFilling: cakeFilling, cakeFrosting: cakeFrosting, coffeeServingTemp: coffeeServingTemp, barPourMetric: barPourMetric, mealPlanInclusions: mealPlanInclusions, eventType: eventType, setupInclusions: setupInclusions, selfMedicationWarning: selfMedicationWarning, controlledRegisterId: controlledRegisterId, masterMoleculeCode: masterMoleculeCode, genericAlternative: genericAlternative, homeopathyLatinName: homeopathyLatinName, homeopathyPotencyScale: homeopathyPotencyScale, homeopathyDilution: homeopathyDilution, homeopathyMotherTincture: homeopathyMotherTincture, biocompatibilityGrade: biocompatibilityGrade, weightCapacity: weightCapacity, rentalPeriod: rentalPeriod, reagentType: reagentType, reagentSensitivity: reagentSensitivity, curingTime: curingTime, settingExpansion: settingExpansion, targetSpecies: targetSpecies, animalWeightRange: animalWeightRange, meatWithdrawalPeriod: meatWithdrawalPeriod, milkWithdrawalPeriod: milkWithdrawalPeriod, activeNutrient: activeNutrient, minStorageTemp: minStorageTemp, maxStorageTemp: maxStorageTemp, maxRoomTempExposure: maxRoomTempExposure, nutrientPercentage: nutrientPercentage, substitutionAllowed: substitutionAllowed, contractPricingEffectiveFrom: contractPricingEffectiveFrom, contractPricingEffectiveTo: contractPricingEffectiveTo, scheduledTrialDate: scheduledTrialDate, promisedDeliveryDate: promisedDeliveryDate);
    _updateSpecializedFields(p, masterTradeSku: masterTradeSku, primaryTradeUnit: primaryTradeUnit, tradeCreditTerms: tradeCreditTerms, temperatureStorage: temperatureStorage, prePackRatio: prePackRatio, shrinkageGrade: shrinkageGrade, materialGrade: materialGrade, freightClass: freightClass, industrialUom: industrialUom, incoterms: incoterms, freightSurcharge: freightSurcharge, gaugeThickness: gaugeThickness, rmaPolicy: rmaPolicy, tierUomMapping: tierUomMapping, returnPolicy: returnPolicy, customsPortOfEntry: customsPortOfEntry, ssccBarcode: ssccBarcode, masterOuterBarcode: masterOuterBarcode, masterCaseRatio: masterCaseRatio, caseMultiplier: caseMultiplier, palletStacking: palletStacking, organicCertification: organicCertification, organicCertNo: organicCertNo, organicCertified: organicCertified, farmTraceabilityId: farmTraceabilityId, harvestDate: harvestDate, serviceCategory: serviceCategory, serviceDeliveryMode: serviceDeliveryMode, serviceDuration: serviceDuration, serviceDurationUnit: serviceDurationUnit, billingModel: billingModel, bufferTime: bufferTime, therapistRoom: therapistRoom, staffCommissionRate: staffCommissionRate, pricingMetric: pricingMetric, careTreatments: careTreatments, allocatedStaff: allocatedStaff, diagnosisCharge: diagnosisCharge, serviceWarranty: serviceWarranty, slaPriority: slaPriority, consultationFormat: consultationFormat, meetingPlatform: meetingPlatform, batchTiming: batchTiming, courseMaterialProvided: courseMaterialProvided, batchSeatCapacity: batchSeatCapacity, membershipFrequency: membershipFrequency, trainerInclusion: trainerInclusion, accessPrivileges: accessPrivileges, admissionFee: admissionFee, pausePolicy: pausePolicy, resourceAssignment: resourceAssignment, advanceBookingHours: advanceBookingHours, advanceDepositPct: advanceDepositPct, buyerCreditLimit: buyerCreditLimit, assignedSalesRepresentative: assignedSalesRepresentative, territoryAllocation: territoryAllocation, isAppointmentRequired: isAppointmentRequired, opticalProductType: opticalProductType, lensIndex: lensIndex, lensCoating: lensCoating, frameParameters: frameParameters, optometrySph: optometrySph, optometryCyl: optometryCyl, optometryAxis: optometryAxis, optometryBaseCurve: optometryBaseCurve, optometryDiameter: optometryDiameter, optometryMoistureContent: optometryMoistureContent, optometryReplacementSchedule: optometryReplacementSchedule, udiCode: udiCode, implantType: implantType, classicalReference: classicalReference, vehicleMake: vehicleMake, vehicleModel: vehicleModel, operatingVoltage: operatingVoltage, mountingType: mountingType, packageForm: packageForm, pinCount: pinCount, networkingDeviceType: networkingDeviceType, portConfig: portConfig, wirelessBandwidth: wirelessBandwidth, iotProtocol: iotProtocol, weatherproofRating: weatherproofRating, poeSupported: poeSupported, rackMountable: rackMountable);
    _updateTraceabilityFields(p, enableBatchTracking: enableBatchTracking, enableExpiryTracking: enableExpiryTracking, batchExpiryMandatory: batchExpiryMandatory, breakBulkAllowed: breakBulkAllowed, caseSerialTracking: caseSerialTracking, mtcRequired: mtcRequired, bulkNarcoticLogging: bulkNarcoticLogging, coldChainLogger: coldChainLogger, expiryWarningThreshold: expiryWarningThreshold, expiryAlertThreshold: expiryAlertThreshold, freshnessDuration: freshnessDuration, freshnessUnit: freshnessUnit, unitsPerStrip: unitsPerStrip, allowLooseBilling: allowLooseBilling, capWeighed: capWeighed, capPluCode: capPluCode, capBulk: capBulk, capRepack: capRepack, capTare: capTare, capCatchWeight: capCatchWeight, capVariant: capVariant, capDeposit: capDeposit, capColdChain: capColdChain, capAgeRestriction: capAgeRestriction, scaleMode: scaleMode, pluType: pluType, bulkSourceProduct: bulkSourceProduct, availableBulkQuantity: availableBulkQuantity, repackSourceProduct: repackSourceProduct, repackConversionRatio: repackConversionRatio, minWeight: minWeight, maxWeight: maxWeight, tareMode: tareMode, minAge: minAge, legalReference: legalReference, depositType: depositType, depositAmount: depositAmount, variantGroup: variantGroup, variantType: variantType, periodAfterOpening: periodAfterOpening, isRecalledBatch: isRecalledBatch, inspectionId: inspectionId, rfidId: rfidId, productRelationship: productRelationship, warrantyInfo: warrantyInfo, warrantyAvailable: warrantyAvailable, warrantyDuration: warrantyDuration, warrantyUnit: warrantyUnit, warrantyContract: warrantyContract, fragranceFamily: fragranceFamily, concentration: concentration, scentNotes: scentNotes, perfumeHouse: perfumeHouse, topNotes: topNotes, middleNotes: middleNotes, baseNotes: baseNotes, ingredients: ingredients, usageInfo: usageInfo, productionLeadTime: productionLeadTime, brandRange: brandRange, skinType: skinType, hairType: hairType, volume: volume, sparePartsBreakdown: sparePartsBreakdown, abv: abv, ageGate: ageGate, baleWeight: baleWeight, rollLength: rollLength, isCatchWeight: isCatchWeight, scaleWeightPrecision: scaleWeightPrecision, variableWeightTolerance: variableWeightTolerance, tareWeightDeduction: tareWeightDeduction, unitPriceComparisonBase: unitPriceComparisonBase, isCrossDockingAllowed: isCrossDockingAllowed, isVmiEnabled: isVmiEnabled, inHouseRepack: inHouseRepack, nicotineContent: nicotineContent, passportVerificationRequired: passportVerificationRequired, flightNumberRequired: flightNumberRequired, multiBuyBundlePrice: multiBuyBundlePrice, multiBuyQtyTrigger: multiBuyQtyTrigger, multiBuyMaxQtyPerBill: multiBuyMaxQtyPerBill, compensationCess: compensationCess, minOrderValue: minOrderValue, temperatureProfile: temperatureProfile, cosmeticGrade: cosmeticGrade, batteryHealth: batteryHealth, sellerWarranty: sellerWarranty, replacedParts: replacedParts, peakOutput: peakOutput, solarChargeController: solarChargeController, nightVision: nightVision, focalLength: focalLength, inverterTechnology: inverterTechnology, dishwasherSafe: dishwasherSafe, originalBoxIncluded: originalBoxIncluded, pureSineWave: pureSineWave, obstacleAvoidance: obstacleAvoidance, nightVisionEnabled: nightVisionEnabled, mandatorySerialScan: mandatorySerialScan, seasonalProduct: seasonalProduct, isFoldable: isFoldable, isMotorized: isMotorized, isRentalAvailable: isRentalAvailable, fastMovingFlag: fastMovingFlag, takeoffWeight: takeoffWeight, flightTime: flightTime, transmissionRange: transmissionRange, batteryChemistry: batteryChemistry, template: template, ageRestriction: ageRestriction, businessScale: businessScale, itemType: itemType, businessType: businessType, businessCategory: businessCategory, stallAssignment: stallAssignment, managementRoyaltyPct: managementRoyaltyPct, foodCategory: foodCategory, ingredientsSummary: ingredientsSummary, dietaryBadges: dietaryBadges, cupSizes: cupSizes, fruitBases: fruitBases, comboItems: comboItems, allowRoomFolio: allowRoomFolio, roomDeliveryCharge: roomDeliveryCharge, takeawaySurcharge: takeawaySurcharge, variableWeightPLU: variableWeightPLU, channelEligibility: channelEligibility, division: division, privateLabel: privateLabel, posHotkeyColor: posHotkeyColor, cancellationPolicy: cancellationPolicy, repairCustomerImei: repairCustomerImei, repairComplaintLog: repairComplaintLog, dataLoggerSerialId: dataLoggerSerialId, sterilizationExpiry: sterilizationExpiry);

    // Fields owned directly by ProductStudioData rather than a grouped updater.
    if (potency != null) p.potency = potency;
    if (stripsPerBox != null) p.stripsPerBox = stripsPerBox;
    if (formulationType != null) p.formulationType = formulationType;
    if (adjuvantVehicle != null) p.adjuvantVehicle = adjuvantVehicle;
    if (servingSize != null) p.servingSize = servingSize;
    if (serviceProcedureType != null) p.serviceProcedureType = serviceProcedureType;
    if (drugLicenseWholesale != null) p.drugLicenseWholesale = drugLicenseWholesale;
    if (productClassification != null) p.productClassification = productClassification;
    if (complianceId != null) p.complianceId = complianceId;
    if (brandType != null) p.brandType = brandType;
    if (barcodeType != null) p.barcodeType = barcodeType;
    if (subDepartment != null) p.subDepartment = subDepartment;
    if (hallmarkCert != null) p.hallmarkCert = hallmarkCert;
    if (manufacturingDate != null) p.manufacturingDate = manufacturingDate;
    if (bakeryShelfLife != null) p.bakeryShelfLife = bakeryShelfLife;
    if (barLiquorClass != null) p.barLiquorClass = barLiquorClass;
    if (minPax != null) p.minPax = minPax;
    if (parentSku != null) p.parentSku = parentSku;

    notify();
  }
}
