import '../product_studio_data.dart';
import '../product_studio_enums.dart';
import '../product.dart';
import '../sku.dart';
import '../barcode.dart';
import '../category.dart';
import '../brand.dart';
import '../unit.dart';
import '../tax_profile.dart';
import '../product_variant.dart';
import '../product_enums.dart';
import '../product_industry_fields.dart';

extension ProductStudioToDomain on ProductStudioData {
  Product toDomain() {
    return Product(
      id: id, name: title, description: description, sku: SKU(sku),
      barcode: barcode.isNotEmpty ? Barcode(barcode) : null,
      unit: Unit(id: '', name: unit, symbol: unit),
      category: category.isNotEmpty ? Category(id: 'temp', name: category) : null,
      brand: brand.isNotEmpty ? Brand(id: 'temp', name: brand) : null,
      taxProfile: taxCode.isNotEmpty ? TaxProfile(id: 'temp', name: taxCode, rate: 0.0) : null,
      basePrice: sellingPrice, baseCost: costPrice, mrp: mrp, wholesalePrice: wholesalePrice,
      discountPct: discountType == "Percentage" ? discountValue : 0,
      discountAmount: discountType == "Amount" ? discountValue : 0,
      openingStock: openingStock, warehouseLocation: warehouseLocation,
      createdAt: DateTime.now(), updatedAt: DateTime.now(),
      itemType: itemType, status: ProductStatus.values.firstWhere((e) => e.name.toLowerCase() == status.toLowerCase(), orElse: () => ProductStatus.active),
      businessScale: businessScale ?? BusinessScale.small,
      manufacturer: manufacturerName, tags: tags.split(',').map((e) => e.trim()).toList(),
      minStock: safetyStock, maxStock: maxStock, reorderLevel: reorderLevel,
      batchTracking: enableBatchTracking, supplierProductName: supplierProductName,
      supplierProductCode: supplierProductCode, supplierPurchaseCost: supplierPurchaseCost,
      supplierMOQ: supplierMOQ, supplierLeadTime: supplierLeadTime, secondarySupplier: secondarySupplier,
      supplierPaymentTerms: supplierPaymentTerms, supplierContact: supplierContact, supplierNotes: supplierNotes,
      businessType: businessType, businessCategory: businessCategory, gstTaxMode: gstTaxMode,
      packageType: packageType, unitsPerPackage: unitsPerPackage, packageQuantity: packageQuantity,
      stockUnit: stockUnit, conversionFactor: conversionFactor,
      industry: ProductIndustryFields(
        material: material, metalType: metalType, purity: purity, weight: weight,
        stoneType: stoneType, stoneWeight: stoneWeight, jewelrySize: jewelrySize,
        shade: shade, skinType: skinType, hairType: hairType, volume: volume,
        ingredients: ingredients, usageInfo: usageInfo, fragranceFamily: fragranceFamily,
        concentration: concentration, gender: gender, scentNotes: scentNotes,
        serialNumber: serialNumber, imei: imei, modelNumber: modelNumber,
        partNumber: partNumber, oemNumber: oemNumber, compatibility: compatibility,
        vehicleMake: vehicleMake, vehicleModel: vehicleModel, styleCategory: styleCategory,
        season: season, soleMaterial: soleMaterial, closureType: closureType,
        widthFit: widthFit, sizeStandard: sizeStandard, apparelCategory: apparelCategory,
        patternDesign: patternDesign, fitType: fitType, sleeveNeckType: sleeveNeckType,
        careGuide: careGuide, artisanLabel: artisanLabel, collectionEdition: collectionEdition,
        productionLeadTime: productionLeadTime, exclusiveSinglePiece: exclusiveSinglePiece,
        madeToOrder: madeToOrder, measurementBust: measurementBust, measurementWaist: measurementWaist,
        measurementHip: measurementHip, measurementFullLength: measurementFullLength,
        gemstoneCount: gemstoneCount, hallmarkCert: hallmarkCert, makingChargeMode: makingChargeMode,
        makingChargeRate: makingChargeRate, wastagePct: wastagePct, liveRateLink: liveRateLink,
        brandRange: brandRange, shadeHexColor: shadeHexColor, safetyCertifications: safetyCertifications,
        periodAfterOpening: periodAfterOpening, perfumeHouse: perfumeHouse, topNotes: topNotes,
        middleNotes: middleNotes, baseNotes: baseNotes, aisleLocation: aisleLocation,
        countryOfOrigin: countryOfOrigin, variableWeightPLU: variableWeightPLU,
        pluCode: pluCode, tareWeight: tareWeight, onlinePrice: onlinePrice,
        maxDiscountPct: maxDiscountPct, channelEligibility: channelEligibility,
        expiryWarningThreshold: expiryWarningThreshold, searchKeywords: searchKeywords,
        promotionalBadges: promotionalBadges, division: division, privateLabel: privateLabel,
        seasonalProduct: seasonalProduct, masterCaseRatio: masterCaseRatio, grossWeight: grossWeight,
        unitDimensions: unitDimensions, packagingDeposit: packagingDeposit,
        importDutyClass: importDutyClass, memberLoyaltyPrice: memberLoyaltyPrice,
        loyaltyPointsMultiplier: loyaltyPointsMultiplier, storageClass: storageClass,
        floorZone: floorZone, organicCertified: organicCertified, foodCategory: foodCategory,
        ingredientsSummary: ingredientsSummary, storageCondition: storageCondition,
        dietaryBadges: dietaryBadges, fastMovingFlag: fastMovingFlag,
        posHotkeyEnabled: posHotkeyEnabled, posHotkeyColor: posHotkeyColor, ageRestriction: ageRestriction,
        readyToEatItem: readyToEatItem, coldStorageIndicator: coldStorageIndicator, multiBarcodes: multiBarcodes,
        marketingTitle: marketingTitle, urlSlug: urlSlug, metaDescription: metaDescription,
        featuredProduct: featuredProduct, productRelationship: productRelationship,
        warrantyInfo: warrantyInfo, warrantyAvailable: warrantyAvailable,
        warrantyDuration: warrantyDuration, warrantyUnit: warrantyUnit,
        cuisineType: cuisineType, kotStation: kotStation, foodClass: foodClass,
        spiceLevel: spiceLevel, allergens: allergens, calories: calories, recipeBOM: recipeBOM,
        portionSize: portionSize, prepTime: prepTime, takeawaySurcharge: takeawaySurcharge,
        serviceChargePct: serviceChargePct, cafeCategory: cafeCategory,
        temperatureProfile: temperatureProfile, cupSizes: cupSizes, milkOptions: milkOptions,
        sugarLevels: sugarLevels, bakeryType: bakeryType, flavorProfile: flavorProfile,
        bakeTimestamp: bakeTimestamp, freshnessDuration: freshnessDuration,
        freshnessUnit: freshnessUnit, juiceCategory: juiceCategory, fruitBases: fruitBases,
        isCombo: isCombo, comboItems: comboItems, hotelDepartment: hotelDepartment,
        allowRoomFolio: allowRoomFolio, roomDeliveryCharge: roomDeliveryCharge,
        virtualBrand: virtualBrand, aggregatorMappings: aggregatorMappings,
        containerType: containerType, packagingCost: packagingCost,
        stallAssignment: stallAssignment, managementRoyaltyPct: managementRoyaltyPct,
        digitalMenuDescription: digitalMenuDescription, preparationSlaWindow: preparationSlaWindow,
        fineDiningCourse: fineDiningCourse, winePairing: winePairing, swiggySku: swiggySku,
        zomatoSku: zomatoSku, uberEatsSku: uberEatsSku, talabatSku: talabatSku,
        cakeSize: cakeSize, cakeShape: cakeShape, cakeFilling: cakeFilling, cakeFrosting: cakeFrosting,
        bakeryShelfLife: bakeryShelfLife, coffeeServingTemp: coffeeServingTemp,
        barLiquorClass: barLiquorClass, barPourMetric: barPourMetric,
        mealPlanInclusions: mealPlanInclusions, eventType: eventType, setupInclusions: setupInclusions,
        kdsCategory: kdsCategory, recipeVersion: recipeVersion, recipePrepNotes: recipePrepNotes,
        cancellationPolicy: cancellationPolicy, repairCustomerImei: repairCustomerImei,
        repairComplaintLog: repairComplaintLog, assignedSalesRepresentative: assignedSalesRepresentative,
        territoryAllocation: territoryAllocation, customsPortOfEntry: customsPortOfEntry,
        ssccBarcode: ssccBarcode, taxExemptionNo: taxExemptionNo, targetAgeGroup: targetAgeGroup,
        therapeuticCategory: therapeuticCategory, indicationCategory: indicationCategory,
        selfMedicationWarning: selfMedicationWarning, drugSchedule: drugSchedule,
        controlledRegisterId: controlledRegisterId, dataLoggerSerialId: dataLoggerSerialId,
        masterMoleculeCode: masterMoleculeCode, genericAlternative: genericAlternative,
        classicalReference: classicalReference, homeopathyLatinName: homeopathyLatinName,
        homeopathyPotencyScale: homeopathyPotencyScale, homeopathyDilution: homeopathyDilution,
        homeopathyMotherTincture: homeopathyMotherTincture, implantType: implantType,
        biocompatibilityGrade: biocompatibilityGrade, udiCode: udiCode,
        weightCapacity: weightCapacity, rentalPeriod: rentalPeriod, optometrySph: optometrySph,
        optometryCyl: optometryCyl, optometryAxis: optometryAxis, optometryBaseCurve: optometryBaseCurve,
        optometryDiameter: optometryDiameter, optometryMoistureContent: optometryMoistureContent,
        optometryReplacementSchedule: optometryReplacementSchedule, reagentType: reagentType,
        reagentSensitivity: reagentSensitivity, curingTime: curingTime,
        settingExpansion: settingExpansion, targetSpecies: targetSpecies,
        animalWeightRange: animalWeightRange, meatWithdrawalPeriod: meatWithdrawalPeriod,
        milkWithdrawalPeriod: milkWithdrawalPeriod, activeNutrient: activeNutrient,
        minStorageTemp: minStorageTemp, maxStorageTemp: maxStorageTemp,
        maxRoomTempExposure: maxRoomTempExposure, nutrientPercentage: nutrientPercentage,
        coldChainRequired: coldChainRequired, substitutionAllowed: substitutionAllowed,
        isFoldable: isFoldable, isMotorized: isMotorized, isRentalAvailable: isRentalAvailable,
        sterilizationExpiry: sterilizationExpiry, harvestDate: harvestDate,
        scheduledTrialDate: scheduledTrialDate, promisedDeliveryDate: promisedDeliveryDate,
        contractPricingEffectiveFrom: contractPricingEffectiveFrom,
        contractPricingEffectiveTo: contractPricingEffectiveTo,
      ),
      batches: batches, supplierRelationships: supplierRelationships,
      variants: variants.map((v) => ProductVariant(
        id: "$id-${v.color}-${v.size}", productId: id, sku: SKU(v.sku),
        barcode: v.barcode.isNotEmpty ? Barcode(v.barcode) : null,
        attributes: {"Color": v.color, "Size": v.size},
        priceAdjustment: v.price - sellingPrice, stockLevel: v.stock.toDouble(),
      )).toList(),
    );
  }
}
