part of '../product_studio_data.dart';

mixin _ProductStudioCommerceFields {
  // Capability Flags (TAB 02)
  bool capWeighed = false;
  bool capPluCode = false;
  bool capBulk = false;
  bool capRepack = false;
  bool capTare = false;
  bool capCatchWeight = false;
  bool capVariant = false;
  bool capDeposit = false;
  bool capColdChain = false;
  bool capAgeRestriction = false;

  // Dynamic Detail Fields (TAB 02)
  String scaleMode = "";
  String pluType = "";
  String bulkSourceProduct = "";
  double availableBulkQuantity = 0.0;
  String repackSourceProduct = "";
  double repackConversionRatio = 0.0;
  double minWeight = 0.0;
  double maxWeight = 0.0;
  String tareMode = "";
  int minAge = 0;
  String legalReference = "";
  String depositType = "";
  double depositAmount = 0.0;
  String variantGroup = "";
  String variantType = "";

  // Enterprise & Commercial
  double costPrice = 0.0;
  double purchaseCost = 0.0;
  double landedCost = 0.0;
  double sellingPrice = 0.0;
  double mrp = 0.0;
  double wholesalePrice = 0.0;
  double onlinePrice = 0.0;
  double memberLoyaltyPrice = 0.0;
  double loyaltyPointsMultiplier = 1.0;
  String discountType = "Percentage";
  double discountValue = 0.0;
  double maxDiscountPct = 0.0;
  bool autoComputeLandedCost = false;
  bool isLiveMarketPrice = false;
  DateTime? priceEffectiveFrom;
  String currency = "USD";
  List<MarketPricing> pricingTiers = [];
  double targetMarginPct = 0.0;
  double targetMarkupPct = 0.0;
  double branchSellingPrice = 0.0;

  // Inventory & Logistics
  bool trackInventory = true;
  bool allowNegativeStock = false;
  double openingStock = 0.0;
  double minStock = 0.0;
  double safetyStock = 0.0;
  double maxStock = 0.0;
  double reorderLevel = 0.0;
  String warehouseLocation = "";
  String stockUnit = "Unit";
  String salesUnit = "Unit";
  String purchaseUnit = "Unit";
  double conversionFactor = 1.0;
  double grossWeight = 0.0;
  double netWeight = 0.0;
  double tareWeight = 0.0;
  String unitDimensions = "";
  String packageType = "";
  int unitsPerPackage = 1;
  double packageQuantity = 0.0;
  double packagingDeposit = 0.0;
  double packagingCost = 0.0;
  double containerDepositFee = 0.0;
  String storageClass = "";
  String storageCondition = "";
  String floorZone = "";
  bool coldStorageIndicator = false;
  bool coldChainRequired = false;
  String logisticsSlab = "";
  String volumetricWeight = "";
  String countryRestrictions = "";
  String valuationMethod = "FIFO";
  int leadTimeBuffer = 0;
  bool autoReplenish = false;
  bool cashierOverride = false;
  double maxCashierDisc = 0.0;
  String planogramAisle = "";
  String planogramBay = "";
  String planogramRack = "";
  String planogramShelf = "";
  String planogramBin = "";
  String planogramEndcap = "";
  String planogramId = "";
  String masterOuterBarcode = "";
  int innerPackQuantity = 0;
  int caseMultiplier = 1;

  // POS & Branch
  String pluCode = "";
  String unit = "Pc";
  String posShortThermalName = "";
  String posReceiptName = "";
  bool isQuickPOSSale = false;
  bool posHotkeyEnabled = false;
  bool posAgeGate = false;
  String posManualDiscount = "";
  String posPriceOverride = "";
  String eslId = "";
  String rfidTagId = "";
  String aisleLocation = "";
  int minDisplayQty = 0;
  int maxDisplayQty = 0;
  bool isEasTagRequired = false;
  bool mandatorySerialScan = false;

  // Taxation & Compliance
  String taxStatus = "Taxable";
  String taxCategory = "Standard";
  double taxRate = 0.0;
  String taxJurisdiction = "Default";
  String taxCode = "";
  String taxTreatment = "";
  String vatCategory = "";
  String selectiveExciseTax = "";
  String zatcaCode = "";
  String sacCode = "";
  String hsnCode = "";
  String taxExemptionNo = "";
  String importDutyClass = "";

  // Suppliers
  String supplier = "";
  String secondarySupplier = "";
  String supplierProductCode = "";
  String supplierProductName = "";
  double supplierPurchaseCost = 0.0;
  int supplierMOQ = 1;
  int supplierLeadTime = 0;
  String supplierPaymentTerms = "";
  String supplierContact = "";
  String supplierNotes = "";
  String primarySupplierId = "";
  String supplierSku = "";
  double vendorContractCost = 0.0;
  double supplierMoq = 0.0;
  List<SupplierRelationship> supplierRelationships = [];
}
