import '../../../domain/models/product_studio_enums.dart';

final Map<String, AuroraStudioTab> fieldToAuroraTab = {
  // TAB 1 ΓÇö IDENTITY
  'title': AuroraStudioTab.identity, 'arabicTitle': AuroraStudioTab.identity,
  'description': AuroraStudioTab.identity, 'sku': AuroraStudioTab.identity,
  'barcode': AuroraStudioTab.identity, 'multiBarcodes': AuroraStudioTab.identity,
  'posShortThermalName': AuroraStudioTab.identity, 'barcodeType': AuroraStudioTab.identity,
  'eslId': AuroraStudioTab.identity, 'productClassification': AuroraStudioTab.identity,
  'brandType': AuroraStudioTab.identity, 'brand': AuroraStudioTab.identity,
  'category': AuroraStudioTab.identity, 'subcategory': AuroraStudioTab.identity,
  'subDepartment': AuroraStudioTab.identity, 'department': AuroraStudioTab.identity,
  'returnPolicy': AuroraStudioTab.identity, 'productLifecycleStatus': AuroraStudioTab.identity,
  'status': AuroraStudioTab.identity, 'gender': AuroraStudioTab.identity,
  'targetAgeGroup': AuroraStudioTab.identity, 'countryOfOrigin': AuroraStudioTab.identity,
  'season': AuroraStudioTab.identity, 'collectionEdition': AuroraStudioTab.identity,
  'healthLicense': AuroraStudioTab.identity, 'genericSalt': AuroraStudioTab.identity,
  'potency': AuroraStudioTab.identity, 'dosageForm': AuroraStudioTab.identity,
  'fineDiningCourse': AuroraStudioTab.identity, 'foodClass': AuroraStudioTab.identity,
  'spiceLevel': AuroraStudioTab.identity, 'prepTime': AuroraStudioTab.identity,
  'packagingSurcharge': AuroraStudioTab.identity, 'freshnessDuration': AuroraStudioTab.identity,
  'freshnessUnit': AuroraStudioTab.identity, 'coldStorageIndicator': AuroraStudioTab.identity,
  'launchDate': AuroraStudioTab.identity, 'effectiveDate': AuroraStudioTab.identity,
  'discontinueDate': AuroraStudioTab.identity, 'priceEffectiveFrom': AuroraStudioTab.identity,

  // TAB 2 ΓÇö PLANOGRAM / PROFILE OPERATIONS
  'floorZone': AuroraStudioTab.planogram, 'planogramId': AuroraStudioTab.planogram,
  'planogramAisle': AuroraStudioTab.planogram, 'planogramBay': AuroraStudioTab.planogram,
  'planogramRack': AuroraStudioTab.planogram, 'planogramShelf': AuroraStudioTab.planogram,
  'planogramBin': AuroraStudioTab.planogram, 'storageClass': AuroraStudioTab.planogram,
  'minDisplayQty': AuroraStudioTab.planogram, 'maxDisplayQty': AuroraStudioTab.planogram,
  'allowLooseBilling': AuroraStudioTab.planogram, 'inHouseRepack': AuroraStudioTab.planogram,
  'conversionFactor': AuroraStudioTab.planogram, 'purchaseUnit': AuroraStudioTab.planogram,
  'unit': AuroraStudioTab.planogram, 'kotStation': AuroraStudioTab.planogram,
  'kdsCategory': AuroraStudioTab.planogram, 'courseFireDelay': AuroraStudioTab.planogram,
  'recipeVersion': AuroraStudioTab.planogram, 'targetFoodCostPct': AuroraStudioTab.planogram,
  'recipePrepNotes': AuroraStudioTab.planogram, 'material': AuroraStudioTab.planogram,
  'fabric': AuroraStudioTab.planogram, 'patternDesign': AuroraStudioTab.planogram,
  'fitType': AuroraStudioTab.planogram, 'sizeScale': AuroraStudioTab.planogram,
  'color': AuroraStudioTab.planogram, 'metalType': AuroraStudioTab.planogram,
  'purity': AuroraStudioTab.planogram, 'stoneType': AuroraStudioTab.planogram,
  'movement': AuroraStudioTab.planogram, 'lensIndex': AuroraStudioTab.planogram,
  'fragranceFamily': AuroraStudioTab.planogram,

  // TAB 3 ΓÇö LOGISTICS & PACKAGING
  'masterOuterBarcode': AuroraStudioTab.logistics, 'outerBarcode': AuroraStudioTab.logistics,
  'outerCartonBarcode': AuroraStudioTab.logistics, 'innerPackQuantity': AuroraStudioTab.logistics,
  'masterCaseMultiplier': AuroraStudioTab.logistics, 'palletStacking': AuroraStudioTab.logistics,
  'grossWeight': AuroraStudioTab.logistics, 'netWeight': AuroraStudioTab.logistics,
  'unitDimensions': AuroraStudioTab.logistics, 'packaging': AuroraStudioTab.logistics,
  'packageType': AuroraStudioTab.logistics, 'packagingCost': AuroraStudioTab.logistics,
  'volumetricWeight': AuroraStudioTab.logistics, 'logisticsSlab': AuroraStudioTab.logistics,

  // TAB 4 ΓÇö PRICING
  'costPrice': AuroraStudioTab.pricing, 'purchaseCost': AuroraStudioTab.pricing,
  'landedCost': AuroraStudioTab.pricing, 'sellingPrice': AuroraStudioTab.pricing,
  'mrp': AuroraStudioTab.pricing, 'wholesalePrice': AuroraStudioTab.pricing,
  'discountValue': AuroraStudioTab.pricing, 'discountType': AuroraStudioTab.pricing,
  'minimumFloorPrice': AuroraStudioTab.pricing, 'targetMarginPct': AuroraStudioTab.pricing,
  'targetMarkupPct': AuroraStudioTab.pricing, 'promoDiscount': AuroraStudioTab.pricing,
  'cashierDiscountOverride': AuroraStudioTab.pricing, 'maxCashierDiscountPct': AuroraStudioTab.pricing,
  'loyaltyMultiplier': AuroraStudioTab.pricing, 'branchStorePrice': AuroraStudioTab.pricing,
  'zoneTier': AuroraStudioTab.pricing, 'priceActivationBatchId': AuroraStudioTab.pricing,
  'scheduledStartDate': AuroraStudioTab.pricing, 'scheduledEndDate': AuroraStudioTab.pricing,

  // TAB 5 ΓÇö STOCK / INVENTORY
  'openingStock': AuroraStudioTab.stock, 'safetyStock': AuroraStudioTab.stock,
  'reorderLevel': AuroraStudioTab.stock, 'warehouseLocation': AuroraStudioTab.stock,
  'trackInventory': AuroraStudioTab.stock, 'valuation': AuroraStudioTab.stock,
  'primaryWarehouse': AuroraStudioTab.stock, 'currentOnHand': AuroraStudioTab.stock,
  'allocatedBopis': AuroraStudioTab.stock, 'leadTimeBuffer': AuroraStudioTab.stock,
  'moq': AuroraStudioTab.stock, 'autoReplenish': AuroraStudioTab.stock,
  'quarantineStock': AuroraStudioTab.stock, 'damagedStock': AuroraStudioTab.stock,
  'inTransitStock': AuroraStudioTab.stock, 'spoilagePct': AuroraStudioTab.stock,
  'breakagePct': AuroraStudioTab.stock, 'returnToVendor': AuroraStudioTab.stock,
  'wastageReasonCode': AuroraStudioTab.stock, 'scrapAccount': AuroraStudioTab.stock,
  'writeOffApprovalTier': AuroraStudioTab.stock,

  // TAB 6 ΓÇö SUPPLIERS / PROCUREMENT
  'supplier': AuroraStudioTab.vendors, 'supplierProductCode': AuroraStudioTab.vendors,
  'supplierPurchaseCost': AuroraStudioTab.vendors, 'supplierMOQ': AuroraStudioTab.vendors,
  'supplierLeadTime': AuroraStudioTab.vendors, 'secondarySupplier': AuroraStudioTab.vendors,
  'primarySupplierId': AuroraStudioTab.vendors, 'supplierSku': AuroraStudioTab.vendors,
  'contractCost': AuroraStudioTab.vendors, 'supplierMoq': AuroraStudioTab.vendors,
  'deliverySchedule': AuroraStudioTab.vendors, 'paymentCreditTerms': AuroraStudioTab.vendors,
  'purchasePackUom': AuroraStudioTab.vendors, 'incoterms': AuroraStudioTab.vendors,

  // TAB 7 ΓÇö TAX & COMPLIANCE
  'taxStatus': AuroraStudioTab.tax, 'taxCategory': AuroraStudioTab.tax,
  'taxRate': AuroraStudioTab.tax, 'taxJurisdiction': AuroraStudioTab.tax,
  'taxCode': AuroraStudioTab.tax, 'gstTaxMode': AuroraStudioTab.tax,
  'gstVatRate': AuroraStudioTab.tax, 'regionalSurchargeCess': AuroraStudioTab.tax,
  'taxInclusiveExclusive': AuroraStudioTab.tax, 'taxCategoryRule': AuroraStudioTab.tax,
  'primaryHsnSac': AuroraStudioTab.tax, 'legalMetrologyDeclaration': AuroraStudioTab.tax,
  'licenseDisplay': AuroraStudioTab.tax, 'mrpMandate': AuroraStudioTab.tax,
  'consumerCareContact': AuroraStudioTab.tax, 'regulatoryBatchText': AuroraStudioTab.tax,
  'importDuty': AuroraStudioTab.tax, 'vatCategory': AuroraStudioTab.tax,
  'selectiveExcise': AuroraStudioTab.tax, 'zatca': AuroraStudioTab.tax,
  'sac': AuroraStudioTab.tax, 'hsn': AuroraStudioTab.tax, 'taxExemption': AuroraStudioTab.tax,

  // TAB 8 ΓÇö MEDIA / CHANNELS / AUDIT
  'marketingTitle': AuroraStudioTab.media, 'metaDescription': AuroraStudioTab.media,
  'urlSlug': AuroraStudioTab.media, 'featuredProduct': AuroraStudioTab.media,
  'isQuickPOSSale': AuroraStudioTab.media, 'visibility': AuroraStudioTab.media,
  'primaryImageUrl': AuroraStudioTab.media, 'galleryUrls': AuroraStudioTab.media,
  'heroImage': AuroraStudioTab.media, 'gallery': AuroraStudioTab.media,
  'posIcon': AuroraStudioTab.media, 'zoomAsset': AuroraStudioTab.media,
  'video': AuroraStudioTab.media, 'asset360': AuroraStudioTab.media,
  'showOnPos': AuroraStudioTab.media, 'showOnApp': AuroraStudioTab.media,
  'showOnWeb': AuroraStudioTab.media, 'quickCommerce': AuroraStudioTab.media,
  'b2bPortal': AuroraStudioTab.media, 'marketplace': AuroraStudioTab.media,
  'seoTitle': AuroraStudioTab.media, 'canonicalUrlSlug': AuroraStudioTab.media,
  'keywords': AuroraStudioTab.media, 'searchPriority': AuroraStudioTab.media,
  'featureHighlights': AuroraStudioTab.media, 'rfidTagId': AuroraStudioTab.media,
  'displayTemplateId': AuroraStudioTab.media, 'lastSyncTime': AuroraStudioTab.media,
  'nfcBeaconId': AuroraStudioTab.media, 'batteryLevel': AuroraStudioTab.media,
  'createdBy': AuroraStudioTab.media, 'createdTimestamp': AuroraStudioTab.media,
  'lastModifiedBy': AuroraStudioTab.media, 'lastModifiedTimestamp': AuroraStudioTab.media,
  'revisionVersion': AuroraStudioTab.media, 'cryptographicAuditHash': AuroraStudioTab.media,
};
