import 'country_models.dart';

const List<CountryProfile> asiaMiddleEastCountries = [
  CountryProfile(
    code: 'AE',
    name: 'United Arab Emirates',
    flagEmoji: '🇦🇪',
    phoneCode: '+971',
    defaultTimezone: 'Asia/Dubai',
    timezones: ['Asia/Dubai'],
    currency: CurrencyProfile(
      code: 'AED',
      symbol: 'AED',
      decimalDigits: 2,
      name: 'UAE Dirham',
      locale: 'ar_AE',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 5.0,
      label: 'VAT',
      taxIdName: 'TRN',
    ),
  ),
  CountryProfile(
    code: 'SA',
    name: 'Saudi Arabia',
    flagEmoji: '🇸🇦',
    phoneCode: '+966',
    defaultTimezone: 'Asia/Riyadh',
    timezones: ['Asia/Riyadh'],
    currency: CurrencyProfile(
      code: 'SAR',
      symbol: 'SAR',
      decimalDigits: 2,
      name: 'Saudi Riyal',
      locale: 'ar_SA',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 15.0,
      label: 'VAT',
      taxIdName: 'VAT Reg No',
    ),
  ),
  CountryProfile(
    code: 'KW',
    name: 'Kuwait',
    flagEmoji: '🇰🇼',
    phoneCode: '+965',
    defaultTimezone: 'Asia/Kuwait',
    timezones: ['Asia/Kuwait'],
    currency: CurrencyProfile(
      code: 'KWD',
      symbol: 'KWD',
      decimalDigits: 3,
      name: 'Kuwaiti Dinar',
      locale: 'en_KW',
    ),
    tax: TaxProfile(
      taxType: TaxType.none,
      defaultRate: 0.0,
      label: 'No Tax',
      taxIdName: 'Tax ID',
    ),
  ),
  CountryProfile(
    code: 'OM',
    name: 'Oman',
    flagEmoji: '🇴🇲',
    phoneCode: '+968',
    defaultTimezone: 'Asia/Muscat',
    timezones: ['Asia/Muscat'],
    currency: CurrencyProfile(
      code: 'OMR',
      symbol: 'OMR',
      decimalDigits: 3,
      name: 'Omani Rial',
      locale: 'ar_OM',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 5.0,
      label: 'VAT',
      taxIdName: 'VAT ID',
    ),
  ),
  CountryProfile(
    code: 'BH',
    name: 'Bahrain',
    flagEmoji: '🇧🇭',
    phoneCode: '+973',
    defaultTimezone: 'Asia/Bahrain',
    timezones: ['Asia/Bahrain'],
    currency: CurrencyProfile(
      code: 'BHD',
      symbol: 'BHD',
      decimalDigits: 3,
      name: 'Bahraini Dinar',
      locale: 'ar_BH',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 10.0,
      label: 'VAT',
      taxIdName: 'VAT ID',
    ),
  ),
  CountryProfile(
    code: 'QA',
    name: 'Qatar',
    flagEmoji: '🇶🇦',
    phoneCode: '+974',
    defaultTimezone: 'Asia/Qatar',
    timezones: ['Asia/Qatar'],
    currency: CurrencyProfile(
      code: 'QAR',
      symbol: 'QAR',
      decimalDigits: 2,
      name: 'Qatari Riyal',
      locale: 'ar_QA',
    ),
    tax: TaxProfile(
      taxType: TaxType.none,
      defaultRate: 0.0,
      label: 'No Tax',
      taxIdName: 'Tax Card No',
    ),
  ),
];
