import 'country_models.dart';
import 'country_data_asia_me.dart';

const Map<String, String> indiaStatesMap = {
  '01': 'Jammu & Kashmir',
  '02': 'Himachal Pradesh',
  '03': 'Punjab',
  '04': 'Chandigarh',
  '05': 'Uttarakhand',
  '06': 'Haryana',
  '07': 'Delhi',
  '08': 'Rajasthan',
  '09': 'Uttar Pradesh',
  '10': 'Bihar',
  '11': 'Sikkim',
  '12': 'Arunachal Pradesh',
  '13': 'Nagaland',
  '14': 'Manipur',
  '15': 'Mizoram',
  '16': 'Tripura',
  '17': 'Meghalaya',
  '18': 'Assam',
  '19': 'West Bengal',
  '20': 'Jharkhand',
  '21': 'Odisha',
  '22': 'Chhattisgarh',
  '23': 'Madhya Pradesh',
  '24': 'Gujarat',
  '25': 'Daman & Diu',
  '26': 'Dadra & Nagar Haveli',
  '27': 'Maharashtra',
  '28': 'Andhra Pradesh (Old)',
  '29': 'Karnataka',
  '30': 'Goa',
  '31': 'Lakshadweep',
  '32': 'Kerala',
  '33': 'Tamil Nadu',
  '34': 'Puducherry',
  '35': 'Andaman & Nicobar Islands',
  '36': 'Telangana',
  '37': 'Andhra Pradesh',
  '38': 'Ladakh',
};

const List<CountryProfile> asiaCountries = [
  CountryProfile(
    code: 'IN',
    name: 'India',
    flagEmoji: '🇮🇳',
    phoneCode: '+91',
    defaultTimezone: 'Asia/Kolkata',
    timezones: ['Asia/Kolkata'],
    currency: CurrencyProfile(
      code: 'INR',
      symbol: '₹',
      decimalDigits: 2,
      name: 'Indian Rupee',
      locale: 'en_IN',
    ),
    tax: TaxProfile(
      taxType: TaxType.gstSplit,
      defaultRate: 18.0,
      label: 'GST (CGST / SGST / IGST)',
      taxIdName: 'GSTIN',
      states: indiaStatesMap,
    ),
  ),
  ...asiaMiddleEastCountries,
  CountryProfile(
    code: 'SG',
    name: 'Singapore',
    flagEmoji: '🇸🇬',
    phoneCode: '+65',
    defaultTimezone: 'Asia/Singapore',
    timezones: ['Asia/Singapore'],
    currency: CurrencyProfile(
      code: 'SGD',
      symbol: 'S\$',
      decimalDigits: 2,
      name: 'Singapore Dollar',
      locale: 'en_SG',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 9.0,
      label: 'GST',
      taxIdName: 'GST Reg No',
    ),
  ),
  CountryProfile(
    code: 'JP',
    name: 'Japan',
    flagEmoji: '🇯🇵',
    phoneCode: '+81',
    defaultTimezone: 'Asia/Tokyo',
    timezones: ['Asia/Tokyo'],
    currency: CurrencyProfile(
      code: 'JPY',
      symbol: '¥',
      decimalDigits: 0,
      name: 'Japanese Yen',
      locale: 'ja_JP',
    ),
    tax: TaxProfile(
      taxType: TaxType.salesTax,
      defaultRate: 10.0,
      label: 'Consumption Tax',
      taxIdName: 'Corporate Number',
    ),
  ),
  CountryProfile(
    code: 'VN',
    name: 'Vietnam',
    flagEmoji: '🇻🇳',
    phoneCode: '+84',
    defaultTimezone: 'Asia/Ho_Chi_Minh',
    timezones: ['Asia/Ho_Chi_Minh'],
    currency: CurrencyProfile(
      code: 'VND',
      symbol: '₫',
      decimalDigits: 0,
      name: 'Vietnamese Dong',
      locale: 'vi_VN',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 10.0,
      label: 'VAT',
      taxIdName: 'Mã số thuế',
    ),
  ),
  CountryProfile(
    code: 'ID',
    name: 'Indonesia',
    flagEmoji: '🇮🇩',
    phoneCode: '+62',
    defaultTimezone: 'Asia/Jakarta',
    timezones: ['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura'],
    currency: CurrencyProfile(
      code: 'IDR',
      symbol: 'Rp',
      decimalDigits: 0,
      name: 'Indonesian Rupiah',
      locale: 'id_ID',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 11.0,
      label: 'PPN / VAT',
      taxIdName: 'NPWP',
    ),
  ),
  CountryProfile(
    code: 'MY',
    name: 'Malaysia',
    flagEmoji: '🇲🇾',
    phoneCode: '+60',
    defaultTimezone: 'Asia/Kuala_Lumpur',
    timezones: ['Asia/Kuala_Lumpur'],
    currency: CurrencyProfile(
      code: 'MYR',
      symbol: 'RM',
      decimalDigits: 2,
      name: 'Malaysian Ringgit',
      locale: 'ms_MY',
    ),
    tax: TaxProfile(
      taxType: TaxType.salesTax,
      defaultRate: 8.0,
      label: 'SST',
      taxIdName: 'SST No',
    ),
  ),
  CountryProfile(
    code: 'TH',
    name: 'Thailand',
    flagEmoji: '🇹🇭',
    phoneCode: '+66',
    defaultTimezone: 'Asia/Bangkok',
    timezones: ['Asia/Bangkok'],
    currency: CurrencyProfile(
      code: 'THB',
      symbol: '฿',
      decimalDigits: 2,
      name: 'Thai Baht',
      locale: 'th_TH',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 7.0,
      label: 'VAT',
      taxIdName: 'Tax ID',
    ),
  ),
  CountryProfile(
    code: 'PH',
    name: 'Philippines',
    flagEmoji: '🇵🇭',
    phoneCode: '+63',
    defaultTimezone: 'Asia/Manila',
    timezones: ['Asia/Manila'],
    currency: CurrencyProfile(
      code: 'PHP',
      symbol: '₱',
      decimalDigits: 2,
      name: 'Philippine Peso',
      locale: 'en_PH',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 12.0,
      label: 'VAT',
      taxIdName: 'TIN',
    ),
  ),
  CountryProfile(
    code: 'LK',
    name: 'Sri Lanka',
    flagEmoji: '🇱🇰',
    phoneCode: '+94',
    defaultTimezone: 'Asia/Colombo',
    timezones: ['Asia/Colombo'],
    currency: CurrencyProfile(
      code: 'LKR',
      symbol: 'Rs',
      decimalDigits: 2,
      name: 'Sri Lankan Rupee',
      locale: 'si_LK',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 18.0,
      label: 'VAT',
      taxIdName: 'TIN',
    ),
  ),
];
