import 'country_models.dart';

const List<CountryProfile> globalCountries = [
  CountryProfile(
    code: 'US',
    name: 'United States',
    flagEmoji: '🇺🇸',
    phoneCode: '+1',
    defaultTimezone: 'America/New_York',
    timezones: [
      'America/New_York',
      'America/Chicago',
      'America/Denver',
      'America/Los_Angeles',
      'America/Anchorage',
      'Pacific/Honolulu'
    ],
    currency: CurrencyProfile(
      code: 'USD',
      symbol: '\$',
      decimalDigits: 2,
      name: 'US Dollar',
      locale: 'en_US',
    ),
    tax: TaxProfile(
      taxType: TaxType.salesTax,
      defaultRate: 7.5,
      label: 'Sales Tax',
      taxIdName: 'EIN / Tax ID',
    ),
  ),
  CountryProfile(
    code: 'GB',
    name: 'United Kingdom',
    flagEmoji: '🇬🇧',
    phoneCode: '+44',
    defaultTimezone: 'Europe/London',
    timezones: ['Europe/London'],
    currency: CurrencyProfile(
      code: 'GBP',
      symbol: '£',
      decimalDigits: 2,
      name: 'British Pound',
      locale: 'en_GB',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 20.0,
      label: 'VAT',
      taxIdName: 'VAT Registration No',
    ),
  ),
  CountryProfile(
    code: 'CA',
    name: 'Canada',
    flagEmoji: '🇨🇦',
    phoneCode: '+1',
    defaultTimezone: 'America/Toronto',
    timezones: [
      'America/Toronto',
      'America/Vancouver',
      'America/Edmonton',
      'America/Winnipeg',
      'America/Halifax'
    ],
    currency: CurrencyProfile(
      code: 'CAD',
      symbol: '\$',
      decimalDigits: 2,
      name: 'Canadian Dollar',
      locale: 'en_CA',
    ),
    tax: TaxProfile(
      taxType: TaxType.salesTax,
      defaultRate: 5.0,
      label: 'GST / HST',
      taxIdName: 'BN / GST No',
    ),
  ),
  CountryProfile(
    code: 'AU',
    name: 'Australia',
    flagEmoji: '🇦🇺',
    phoneCode: '+61',
    defaultTimezone: 'Australia/Sydney',
    timezones: [
      'Australia/Sydney',
      'Australia/Melbourne',
      'Australia/Brisbane',
      'Australia/Perth',
      'Australia/Adelaide'
    ],
    currency: CurrencyProfile(
      code: 'AUD',
      symbol: 'A\$',
      decimalDigits: 2,
      name: 'Australian Dollar',
      locale: 'en_AU',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 10.0,
      label: 'GST',
      taxIdName: 'ABN',
    ),
  ),
  CountryProfile(
    code: 'DE',
    name: 'Germany',
    flagEmoji: '🇩🇪',
    phoneCode: '+49',
    defaultTimezone: 'Europe/Berlin',
    timezones: ['Europe/Berlin'],
    currency: CurrencyProfile(
      code: 'EUR',
      symbol: '€',
      decimalDigits: 2,
      name: 'Euro',
      locale: 'de_DE',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 19.0,
      label: 'MwSt / VAT',
      taxIdName: 'USt-IdNr',
    ),
  ),
  CountryProfile(
    code: 'FR',
    name: 'France',
    flagEmoji: '🇫🇷',
    phoneCode: '+33',
    defaultTimezone: 'Europe/Paris',
    timezones: ['Europe/Paris'],
    currency: CurrencyProfile(
      code: 'EUR',
      symbol: '€',
      decimalDigits: 2,
      name: 'Euro',
      locale: 'fr_FR',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 20.0,
      label: 'TVA / VAT',
      taxIdName: 'TVA Intracommunautaire',
    ),
  ),
  CountryProfile(
    code: 'ZA',
    name: 'South Africa',
    flagEmoji: '🇿🇦',
    phoneCode: '+27',
    defaultTimezone: 'Africa/Johannesburg',
    timezones: ['Africa/Johannesburg'],
    currency: CurrencyProfile(
      code: 'ZAR',
      symbol: 'R',
      decimalDigits: 2,
      name: 'South African Rand',
      locale: 'en_ZA',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 15.0,
      label: 'VAT',
      taxIdName: 'VAT Number',
    ),
  ),
  CountryProfile(
    code: 'NG',
    name: 'Nigeria',
    flagEmoji: '🇳🇬',
    phoneCode: '+234',
    defaultTimezone: 'Africa/Lagos',
    timezones: ['Africa/Lagos'],
    currency: CurrencyProfile(
      code: 'NGN',
      symbol: '₦',
      decimalDigits: 2,
      name: 'Nigerian Naira',
      locale: 'en_NG',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 7.5,
      label: 'VAT',
      taxIdName: 'TIN',
    ),
  ),
  CountryProfile(
    code: 'KE',
    name: 'Kenya',
    flagEmoji: '🇰🇪',
    phoneCode: '+254',
    defaultTimezone: 'Africa/Nairobi',
    timezones: ['Africa/Nairobi'],
    currency: CurrencyProfile(
      code: 'KES',
      symbol: 'KSh',
      decimalDigits: 2,
      name: 'Kenyan Shilling',
      locale: 'en_KE',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 16.0,
      label: 'VAT',
      taxIdName: 'KRA PIN',
    ),
  ),
  CountryProfile(
    code: 'EG',
    name: 'Egypt',
    flagEmoji: '🇪🇬',
    phoneCode: '+20',
    defaultTimezone: 'Africa/Cairo',
    timezones: ['Africa/Cairo'],
    currency: CurrencyProfile(
      code: 'EGP',
      symbol: 'E£',
      decimalDigits: 2,
      name: 'Egyptian Pound',
      locale: 'ar_EG',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 14.0,
      label: 'VAT',
      taxIdName: 'Tax Reg No',
    ),
  ),
  CountryProfile(
    code: 'BR',
    name: 'Brazil',
    flagEmoji: '🇧🇷',
    phoneCode: '+55',
    defaultTimezone: 'America/Sao_Paulo',
    timezones: ['America/Sao_Paulo', 'America/Manaus', 'America/Recife'],
    currency: CurrencyProfile(
      code: 'BRL',
      symbol: 'R\$',
      decimalDigits: 2,
      name: 'Brazilian Real',
      locale: 'pt_BR',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 17.0,
      label: 'ICMS / VAT',
      taxIdName: 'CNPJ',
    ),
  ),
  CountryProfile(
    code: 'MX',
    name: 'Mexico',
    flagEmoji: '🇲🇽',
    phoneCode: '+52',
    defaultTimezone: 'America/Mexico_City',
    timezones: ['America/Mexico_City', 'America/Cancun', 'America/Tijuana'],
    currency: CurrencyProfile(
      code: 'MXN',
      symbol: '\$',
      decimalDigits: 2,
      name: 'Mexican Peso',
      locale: 'es_MX',
    ),
    tax: TaxProfile(
      taxType: TaxType.vat,
      defaultRate: 16.0,
      label: 'IVA / VAT',
      taxIdName: 'RFC',
    ),
  ),
];
